### ISSUE TITLE
【未完成】纯纯写作 vs. 熊掌记 —— 两个不同片头的编辑器碰在一起的神奇反应 | imgradeone 的新小窝

### ISSUE THREAD

**Issue by imgradeone** [imgradeone/blog#5]
https://blog.imgradeone.xyz/post/wei-wan-cheng-chun-chun-xie-zuo-vs-xiong-zhang-ji-liang-ge-bu-tong-pian-tou-de-bian-ji-qi-peng-zai-yi-qi-de-shen-qi-fan-ying/ 

 imgradeone's new blog

**Comment by Dobby233Liu** [comment]
https://github.com/imgradeone/blog/commit/a54b4e227267744ee6996735a5aa46c4bd74f7f1#r35385959

**Comment by imgradeone** [comment]
> @Dobby233Liu
> https://github.com/imgradeone/blog/commit/a54b4e227267744ee6996735a5aa46c4bd74f7f1#r35385959

草，忘了（（（
