### ISSUE TITLE
交友可以吗？

### ISSUE THREAD

**Issue by ctOS5** [imgradeone/blog#7]
我是55班的同学
你是学go 的吧
我是java 
你这个网页是用sdk 自动生成的吗？
还是自己用html+css+js写的
我留个名啊
ctOS5

**Comment by ctOS5** [comment]
Hhh

**Comment by ctOS5** [comment]
看了一下源代码
还是SDK 生成的
不过也可以
我spring 还没成功过一次呢

**Comment by imgradeone** [comment]
用的是 Gridea，https://gridea.dev

**Comment by ctOS5** [comment]
我自己也发现了一个叫halo 的基于spring 的博客网页生成器，GitHub上有

**Comment by ctOS5** [comment]
加QQ方便聊

**Comment by imgradeone** [comment]
其实邮箱也可以的，imgradeone@outlook.com
